name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # 백엔드로 DB 요청을 보내기 위한 패키지 GET POST PUT DELETE
  # dio 사용할 것
#  http: ^1.1.0
  dio: ^5.4.0
  # 상태 관리 패키지 데이터를 공유하고 관리할 수 있다.uuid
  # riverPod 사용할 것
  provider: ^6.1.1
  # 날짜/숫자 포멧 다국어
  # easy_loacalization 다국어 지원 시 사용할 것
  intl: ^0.18.1
  # navigation의 향상된 버전
  # 경로 이동 사용
  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  # 로그인 상태 저장 모듈
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
