name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # 백엔드로 DB 요청을 보내기 위한 패키지 GET POST PUT DELETE
  # dio 사용할 것
#  http: ^1.1.0
  dio: ^5.4.0
  # 상태 관리 패키지 데이터를 공유하고 관리할 수 있다.uuid
  # riverPod 사용할 것
  provider: ^6.1.1
  # 날짜/숫자 포멧 다국어
  # easy_loacalization 다국어 지원 시 사용할 것
  intl: ^0.18.1
  # navigation의 향상된 버전
  # 경로 이동 사용
  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  # 로그인 상태 저장 모듈
  shared_preferences: ^2.1.1
  # 카카오 맵 플러그인 JavaScript 키를 가져와서 위젯으로 포장한다음 풍부하게 기능 활용하겠다.
  kakao_map_plugin: ^0.3.7
  # 내 위치(GPS) 좌표를 가져오는 도구
  # 생각해보기 -> Android IOS : 에 위치 관련 권한 추가
  geolocator: ^13.0.1
  # dot = .    env    dotenv: =.env
  flutter_dotenv: ^5.1.0

  # 스마트폰 네트워크 모바일 or 와이파이 연결되어 있는지 상태관리
  connectivity_plus: ^6.0.5 # 네트워크 연결 체크
  internet_connection_checker_plus: ^2.5.2 #실제 인터넷 연결 체크


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - .env.development
    - .env.local
    - .env.production
